In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../outputs/miniexon_aa_seq_curated.csv')

In [4]:
df['aa_seq_marked'] = df.apply(lambda x:('#'+x['exon_aa_seq'].split('*')[0]+'#').join(x['aa_seq'].split(x['exon_aa_seq'].split('*')[0])), axis=1)

/tmp/ipykernel_2998386/475835397.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['aa_seq_marked'] = df.apply(lambda x:('#'+x['exon_aa_seq'].split('*')[0]+'#').join(x['aa_seq'].split(x['exon_aa_seq'].split('*')[0])), axis=1)

In [7]:
df_cur = pd.read_csv('../source_data/metadata.csv')

In [8]:
cur_map = df_cur.drop_duplicates("EVENT").set_index("EVENT")["aa_seq_marked"]
df_map = df.drop_duplicates("EVENT").set_index("EVENT")["aa_seq_marked"]

result = [
    cur_map.get(event, df_map.get(event))
    for event in df["EVENT"]
]

In [9]:
df['aa_seq_marked'] = result

In [10]:
df['#'] = df.apply(lambda x:x['aa_seq_marked'].count('#'), axis=1)

In [11]:
df[df['#'] !=2]

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,GENE,EVENT,COORD,LENGTH,Whole_Brain_b,Cortex,Frontal_Gyrus_young,...,Muscle_e,ratio,exon_aa_seq,EventID,IsoformType,IsoformID,Ass,aa_seq,aa_seq_marked,#
94,95,95,60496,VTI1A,HsaEX0070740,chr10:112533530-112533550,21,72.58,41.90,87.41,...,20.00,19.617811,LIKLREE,HsaEX0070740,Excl_main,ENSP00000376792,hg38,MSSDFEGYEQDFAVLTAEITSKIARVPRLPPDEKKQMVANVEKQLE...,MSSDFEGYEQDFAVLTAEITSKIARVPRLPPDEKKQMVANVEKQLE...,0
95,96,97,61524,TMEM87B,HsaEX1041334,chr2:112095228-112095299,72,35.14,64.71,66.67,...,20.00,13.315021,VSDSDLVLLASLPLSLLDSGLCWW,HsaEX1041334,Excl_main,ENSP00000283206,hg38,MVAACRSVAGLLPRRRRCFPARAPLLRVALCLLCWTPAAVRAVPEL...,MVAACRSVAGLLPRRRRCFPARAPLLRVALCLLCWTPAAVRAVPEL...,0
206,207,208,166169,FRY,HsaEX0026448,chr13:32257964-32257972,9,83.77,68.88,86.40,...,71.05,18.662390,ELQ,HsaEX0026448,Excl_main,ENSP00000445043,hg38,MASQQDSGFFEISIKYLLKSWSNTSPVGNGYIKPPVPPASGTHREK...,MASQQDSGFFEISIKYLLKSWSNTSPVGNGYIKPPVPPASGTHREK...,8

In [12]:
df.to_csv('../outputs/miniexon_aa_seq_marked_curated.csv')

In [5]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,GENE,exon_aa_seq,aa_seq,aa_seq_marked,#,EVENT,...,WBC_d,WBC_e,ratio,exon_aa_seq.1,EventID,IsoformType,IsoformID,Ass,aa_seq.1,protein_length
0,0,222,222,167582,AP1S2,DAK,MCSFLEWRDLKIVYKRYASLYFCCAIEDQDNELITLEIIHRYVELL...,MCSFLEWRDLKIVYKRYASLYFCCAIEDQDNELITLEIIHRYVELL...,2,HsaEX0004907,...,0.00,0.11,13.536568,DAK,HsaEX0004907,Incl_main,ENSP00000444957,hg38,MCSFLEWRDLKIVYKRYASLYFCCAIEDQDNELITLEIIHRYVELL...,116
1,1,195,195,158765,STUM,ISQ,MEPSHKDAETAAAAAAVAAADPRGASSSSGVVVQVREKKGPLRAAI...,MEPSHKDAETAAAAAAVAAADPRGASSSSGVVVQVREKKGPLRAAI...,2,HsaEX0010376,...,NaN,NaN,11.844074,ISQ,HsaEX0010376,Incl_main,ENSP00000355752,hg38,MEPSHKDAETAAAAAAVAAADPRGASSSSGVVVQVREKKGPLRAAI...,141
2,2,16,16,9209,GAS2,GFGGQ*,MCTALSPKVRSGPGLSDMHQYSQWLASRHEANLLPMKEDLALWLTN...,MCTALSPKVRSGPGLSDMHQYSQWLASRHEANLLPMKEDLALWLTN...,2,HsaEX0027061,...,NaN,NaN,16.422783,GFGGQ*LCFIYFSEKESTQQEKGLLSAV*HAN,HsaEX0027061,Incl_main,ENST00000278187fB2881,hg38,NaN,141
3,3,223,223,167594,EWSR1,EGTST,MASTDYSTYSQAAAQQGYSAYTAQPTQGYAQTTQQAYGQQSYGTYG...,MASTDYSTYSQAAAQQGYSAYTAQPTQGYAQTTQQAYGQQSYGTYG...,2,HsaEX1013573,...,NaN,NaN,5.031996,EGTST,HsaEX1013573,Incl_main,ENSP00000405947,hg38,MASTDYSTYSQAAAQQGYSAYTAQPTQGYAQTTQQAYGQQSYGTYG...,166
4,4,93,93,64070,FAIM,MASGDDSPIFEDDESPPYSLEK,MASGDDSPIFEDDESPPYSLEKMTDLVAVWDVALSDGVHKIEFEHG...,#MASGDDSPIFEDDESPPYSLEK#MTDLVAVWDVALSDGVHKIEFE...,2,HsaEX0023714,...,0.00,0.00,5.241467,Nan,HsaEX0023714,Incl_main,ENSP00000353775,hg38,MASGDDSPIFEDDESPPYSLEKMTDLVAVWDVALSDGVHKIEFEHG...,201
5,5,99,99,67243,MEAF6,SPSGMFDYDF,MAMHNKAAPPQIPDTRRELAELVKRKQELAETLANLERQIYAFEGS...,MAMHNKAAPPQIPDTRRELAELVKRKQELAETLANLERQIYAFEGS...,2,HsaEX0038484,...,0.70,1.16,19.167401,SPSGMFDYDF,HsaEX0038484,Incl_main,ENSP00000362166,hg38,MAMHNKAAPPQIPDTRRELAELVKRKQELAETLANLERQIYAFEGS...,201
6,6,181,181,149597,CLTB,RIADKAFYQQPDADIIGY,MADDFGFFSSSESGAPEAAEEDPAAAFLAQQESEIAGIENDEGFGA...,MADDFGFFSSSESGAPEAAEEDPAAAFLAQQESEIAGIENDEGFGA...,2,HsaEX0015811,...,0.09,0.39,20.548663,RIADKAFYQQPDADIIGY,HsaEX0015811,Incl_main,ENSP00000309415,hg38,MADDFGFFSSSESGAPEAAEEDPAAAFLAQQESEIAGIENDEGFGA...,229
7,7,139,139,105990,TPD52L2,SSYSIRHSISMPAM,MDSAGQDINLNSPNKGLLSDSMTDVPVDTGVAARTPAVEGLTEAEE...,MDSAGQDINLNSPNKGLLSDSMTDVPVDTGVAARTPAVEGLTEAEE...,2,HsaEX0066666,...,0.25,0.65,19.693020,SSYSIRHSISMPAM,HsaEX0066666,Incl_main,ENSP00000217121,hg38,MDSAGQDINLNSPNKGLLSDSMTDVPVDTGVAARTPAVEGLTEAEE...,229
8,8,229,229,477724,TPD52,KLQAFSHSF,MDCREMDLYEDYQSPFDFDAGVNKSYLYLSPSGNSSPPGSPTLQKF...,MDCREMDLYEDYQSPFDFDAGVNKSYLYLSPSGNSSPPGSPTLQKF...,2,HsaEX0066655,...,1.72,0.80,33.963134,KLQAFSHSF,HsaEX0066655,Incl_main,ENSP00000429351,hg38,MDCREMDLYEDYQSPFDFDAGVNKSYLYLSPSGNSSPPGSPTLQKF...,233
9,9,111,111,78705,MAP7D2,GESENTPPPPLGLAASTLPPDAGTTAAAAESTN,MERGGGGSGTGSRPEGTARGTSLPGKIAEPGAVRTSQPNYRPQGME...,MERGGGGSGTGSRPEGTARGTSLPGKIAEPGAVRTSQPNYRPQGME...,2,HsaEX0037705,...,0.00,0.00,22.688116,GESENTPPPPLGLAASTLPPDAGTTAAAAESTN,HsaEX0037705,Incl_main,ENST00000379643fB4094,hg38,NaN,234
10,10,46,46,26175,TPD52,NIRSIQHSISMPAM,MDCREMDLYEDYQSPFDFDAGVNKSYLYLSPSGNSSPPGSPTLQKF...,MDCREMDLYEDYQSPFDFDAGVNKSYLYLSPSGNSSPPGSPTLQKF...,2,HsaEX0066658,...,0.00,0.00,37.273514,NIRSIQHSISMPAM,HsaEX0066658,Incl_main,ENSP00000410222,hg38,MDCREMDLYEDYQSPFDFDAGVNKSYLYLSPSGNSSPPGSPTLQKF...,238
11,11,146,146,113810,PIKFYVE,DNSLQHPQENT,MATDDKTSPTLDSANDLPRSPTSPSHLTHFKPLTPDQDEPPFKSAY...,MATDDKTSPTLDSANDLPRSPTSPSHLTHFKPLTPDQDEPPFKSAY...,2,HsaEX0047614,...,5.34,5.09,5.334494,DNSLQHPQENT,HsaEX0047614,Incl_main,ENSP00000414477,hg38,MATDDKTSPTLDSANDLPRSPTSPSHLTHFKPLTPDQDEPPFKSAY...,241
12,12,124,124,96848,FAM168A,EFQFLHSAY,MNPVYSPVQPGAPYGNPKNMAYTGYPTAYPAAAPAYNPSLYPTNSP...,MNPVYSPVQPGAPYGNPKNMAYTGYPTAYPAAAPAYNPSLYPTNSP...,2,HsaEX0024131,...,1.50,5.14,5.140212,EFQFLHSAY,HsaEX0024131,Incl_main,ENSP00000064778,hg38,MNPVYSPVQPGAPYGNPKNMAYTGYPTAYPAAAPAYNPSLYPTNSP...,244
13,13,65,65,44695,SSR1,MQSRR,MRLLPRLLLLLLLVFPATVLFRGGPRGLLAVAQDLTEDEETVEDSI...,MRLLPRLLLLLLLVFPATVLFRGGPRGLLAVAQDLTEDEETVEDSI...,2,HsaEX0061917,...,0.00,0.00,42.591059,MQSRR,HsaEX0061917,Incl_main,ENSP00000418617,hg38,MRLLPRLLLLLLLVFPATVLFRGGPRGLLAVAQDLTEDEETVEDSI...,298
14,14,29,29,15067,ASPH,AKAKDFRYNLSEVLQ,MAQRKNAKSSGNSSSSGSGSGSTSAGSSSPGARRETKHGGHKNGRK...,MAQRKNAKSSGNSSSSGSGSGSTSAGSSSPGARRETKHGGHKNGRK...,2,HsaEX0006332,...,3.42,4.50,7.343113,AKAKDFRYNLSEVLQ,HsaEX0006332,Incl_main,ENSP00000427823,hg38,MAQRKNAKSSGNSSSSGSGSGSTSAGSSSPGARRETKHGGHKNGRK...,327
15,15,161,161,132990,FBXO25,DYHLALLFK,MPFLGQDWRSPGWSWIKTEDGWKRCESCSQKLERENNRCNISHSII...,MPFLGQDWRSPGWSWIKTEDGWKRCESCSQKLERENNRCNISHSII...,2,HsaEX0025270,...,1.77,2.27,20.895605,DYHLALLFK,HsaEX0025270,Incl_main,ENSP00000372274,hg38,MPFLGQDWRSPGWSWIKTEDGWKRCESCSQKLERENNRCNISHSII...,367
16,16,51,51,27795,RRAGB,ILDRIHSLQINSSLSTYSLVDSVGNTKT,MEESDSEKTTEKENLGPRMDPPLGEPEGSLGWVLPNTAMKKKVLLM...,MEESDSEKTTEKENLGPRMDPPLGEPEGSLGWVLPNTAMKKKVLLM...,2,HsaEX0055716,...,0.00,0.00,5.720399,ILDRIHSLQINSSLSTYSLVDSVGNTKT,HsaEX0055716,Incl_main,ENSP00000262850,hg38,MEESDSEKTTEKENLGPRMDPPLGEPEGSLGWVLPNTAMKKKVLLM...,374
17,17,106,106,72887,FEZ2,RFSMEGISNVIQNGLRHTFGNSGGEKQ,MAADGDWQDFYEFQEPARSLLDQENCNASPEPGAEAGAEAGGGADG...,MAADGDWQDFYEFQEPARSLLDQENCNASPEPGAEAGAEAGGGADG...,2,HsaEX0025589,...,10.68,16.02,5.970336,RFSMEGISNVIQNGLRHTFGNSGGEKQ,HsaEX0025589,Incl_main,ENSP00000368547,hg38,MAADGDWQDFYEFQEPARSLLDQENCNASPEPGAEAGAEAGGGADG...,380
18,18,54,54,30118,SH3GLB1,IWAEEVTK,MNIMDFNVKKLAADAGTFLSRAVQFTEEKLGQAEKTELDAHLENLL...,MNIMDFNVKKLAADAGTFLSRAVQFTEEKLGQAEKTELDAHLENLL...,2,HsaEX0058023,...,0.85,1.98,11.880678,IWAEEVTK,HsaEX0058023,Incl_main,ENSP00000418744,hg38,MNIMDFNVKKLAADAGTFLSRAVQFTEEKLGQAEKTELDAHLENLL...,386
19,19,135,135,104540,SH3GLB1,QLNSARLEGDNIM,MNIMDFNVKKLAADAGTFLSRAVQFTEEKLGQAEKTELDAHLENLL...,MNIMDFNVKKLAADAGTFLSRAVQFTEEKLGQAEKTELDAHLENLL...,2,HsaEX0058019,...,0.38,1.04,10.102056,QLNSARLEGDNIM,HsaEX0058019,Incl_main,ENSP00000418744,hg38,MNIMDFNVKKLAADAGTFLSRAVQFTEEKLGQAEKTELDAHLENLL...,386
20,20,210,210,166725,ERGIC3,VHAVE,MEALGKLKQFDAYPKTLEDFRVKTCGGATVTIVSGLLMLLLFLSEL...,MEALGKLKQFDAYPKTLEDFRVKTCGGATVTIVSGLLMLLLFLSEL...,2,HsaEX0023051,...,0.35,0.27,31.853887,VHAVE,HsaEX0023051,Incl_main,ENSP00000349970,hg38,MEALGKLKQFDAYPKTLEDFRVKTCGGATVTIVSGLLMLLLFLSEL...,388
21,21,178,178,147865,CERS6,AGKWNPLH,MAGILAWFWNERFWLPHNVTWADLKNTEEATFPQAEDLYLAFPLAF...,MAGILAWFWNERFWLPHNVTWADLKNTEEATFPQAEDLYLAFPLAF...,2,HsaEX0035450,...,0.00,0.00,30.875475,AGKWNPLH,HsaEX0035450,Incl_main,ENSP00000376453,hg38,MAGILAWFWNERFWLPHNVTWADLKNTEEATFPQAEDLYLAFPLAF...,392
22,22,162,162,133355,SH3GLB2,SQGAI,MDFNMKKLASDAGIFFTRAVQFTEEKFGQAEKTELDAHFENLLARA...,MDFNMKKLASDAGIFFTRAVQFTEEKFGQAEKTELDAHFENLLARA...,2,HsaEX0058029,...,1.50,1.37,17.480416,Nan,HsaEX0058029,Incl_main,ENSP00000361634,hg38,MDFNMKKLASDAGIFFTRAVQFTEEKFGQAEKTELDAHFENLLARA...,404
23,23,152,152,124948,KIAA0513,RGDAGEEEEK,METPEVPVGSLIDFGPEAPTSSPLEAPPPVLQDGDGSLGDGASESE...,METPEVPVGSLIDFGPEAPTSSPLEAPPPVLQDGDGSLGDGASESE...,2,HsaEX0033671,...,1.24,3.28,30.796179,RGDAGEEEEK,HsaEX0033671,Incl_main,ENSP00000258180,hg38,NaN,411
24,24,62,62,42409,ATL2,RSPRK,MDTQGAFDSQSTIKDCATVFALSTMTSSVQVYNLSQNIQEDDLQHL...,MDTQGAFDSQSTIKDCATVFALSTMTSSVQVYNLSQNIQEDDLQHL...,2,HsaEX0006689,...,0.00,0.00,19.053519,RSPRK,HsaEX0006689,Incl_main,ENSP00000385446,hg38,MDTQGAFDSQSTIKDCATVFALSTMTSSVQVYNLSQNIQEDDLQHL...,413
25,25,140,140,106052,ARFGAP1,FWGHKQQPEP,MASPRTRKVLKEVRVQDENNVCFECGAFNPQWVSVTYGIWICLECS...,MASPRTRKVLKEVRVQDENNVCFECGAFNPQWVSVTYGIWICLECS...,2,HsaEX0005316,...,0.96,0.59,56.107190,FWGHKQQPEP,HsaEX0005316,Incl_main,ENSP00000314615,hg38,MASPRTRKVLKEVRVQDENNVCFECGAFNPQWVSVTYGIWICLECS...,414
26,26,20,20,9932,ZFYVE27,ETHLVVL,MQTSEREGSGPELSPSVMPEAPLESPPFPTKSPAFDLFNLVLSYKR...,MQTSEREGSGPELSPSVMPEAPLESPPFPTKSPAFDLFNLVLSYKR...,2,HsaEX0072774,...,1.15,0.00,70.953931,ETHLVVL,HsaEX0072774,Incl_main,ENSP00000409594,hg38,MQTSEREGSGPELSPSVMPEAPLESPPFPTKSPAFDLFNLVLSYKR...,416
27,27,34,34,22311,MAPK9,VDIWSVGCIMAEMVLHKVLFPGRD,MSDSKCDSQFYSVQVADSTFTVLKRYQQLKPIGSGAQGIVCAAFDT...,MSDSKCDSQFYSVQVADSTFTVLKRYQQLKPIGSGAQGIVCAAFDT...,2,HsaEX0037799,...,1.15,1.80,17.693282,VDIWSVGCIMAEMVLHKVLFPGRD,HsaEX0037799,Incl_main,ENSP00000389338,hg38,MSDSKCDSQFYSVQVADSTFTVLKRYQQLKPIGSGAQGIVCAAFDT...,424
28,28,56,56,35574,MAPK8,VDLWSVGCIMGEMVCHKILFPGRD,MSRSKRDNNFYSVEIGDSTFTVLKRYQNLKPIGSGAQGIVCAAYDA...,MSRSKRDNNFYSVEIGDSTFTVLKRYQNLKPIGSGAQGIVCAAYDA...,2,HsaEX0037783,...,5.88,6.38,8.736222,VDLWSVGCIMGEMVCHKILFPGRD,HsaEX0037783,Incl_main,ENSP00000363304,hg38,MSRSKRDNNFYSVEIGDSTFTVLKRYQNLKPIGSGAQGIVCAAYDA...,427
29,29,206,206,166331,PACSIN2,DE,MSVTYDDSVGVEVSSDSFWEVGNYKRTVKRIDDGHRLCSDLMNCLH...,MSVTYDDSVGVEVSSDSFWEVGNYKRTVKRIDDGHRLCSDLMNCLH...,2,HsaEX0045196,...,1.32,1.19,17.431040,DE,HsaEX0045196,Incl_main,ENSP00000489297,hg38,MSVTYDDSVGVEVSSDSFWEVGNYKRTVKRIDDGHRLCSDLMNCLH...,451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,201,21,21,10590,SHANK1,SLMDGIGPG,MTHSPATSEDEERHSASECPEGGSESDSSPDGPGRGPRGTRGQGSG...,MTHSPATSEDEERHSASECPEGGSESDSSPDGPGRGPRGTRGQGSG...,2,HsaEX0058111,...,0.00,NaN,7.018980,SLMDGIGPG,HsaEX0058111,Incl_main,ENSP00000375690,hg38,MTHSPATSEDEERHSASECPEGGSESDSSPDGPGRGPRGTRGQGSG...,2169
202,202,168,168,137635,CACNA1D,PTESENVPVPTATPG,MMMMMMMKKMQHQRQQQADHANEANYARGTRLPLSGEGPTSQPNSS...,MMMMMMMKKMQHQRQQQADHANEANYARGTRLPLSGEGPTSQPNSS...,2,HsaEX0011964,...,0.00,0.00,5.178352,PTESENVPVPTATPG,HsaEX0011964,Incl_main,ENSP00000288139,hg38,MMMMMMMKKMQHQRQQQADHANEANYARGTRLPLSGEGPTSQPNSS...,2181
203,203,213,213,166881,DOCK10,AV,MAGERTRRFTRSLLRPGQAAELRHSAASAAAVAVSSRQQQRQEKPR...,MAGERTRRFTRSLLRPGQAAELRHSAASAAAVAVSSRQQQRQEKPR...,2,HsaEX0020538,...,0.00,0.00,17.221023,Nan,HsaEX0020538,Incl_main,ENSP00000437947,hg38,XYDIHRSYLKVAEVVNSEKRLFGRYYRVAFYGQAVGFFEEEEGKEY...,2188
204,204,190,190,157671,CACNA1E,ANAL,MARFGEAVVARPGSGDGDSDQSRNRQGTPVPASGQAAAYKQTKAQR...,MARFGEAVVARPGSGDGDSDQSRNRQGTPVPASGQAAAYKQTKAQR...,2,HsaEX0011970,...,0.00,0.00,inf,ANAL,HsaEX0011970,Incl_main,ENSP00000356545,hg38,MARFGEAVVARPGSGDGDSDQSRNRQGTPVPASGQAAAYKQTKAQR...,2313
205,205,0,0,171,CACNA1G,EISKREDASGQLSCIQLPVDSQG,MDEEEDGAGAEESGQPRSFMRLNDLSGAGGRPGPGSAEKDPGSADS...,MDEEEDGAGAEESGQPRSFMRLNDLSGAGGRPGPGSAEKDPGSADS...,2,HsaEX0011980,...,NaN,NaN,5.089609,EISKREDASGQLSCIQLPVDSQG,HsaEX0011980,Incl_main,ENSP00000352011,hg38,MDEEEDGAGAEESGQPRSFMRLNDLSGAGGRPGPGSAEKDPGSADS...,2377
206,206,6,6,1964,DOPEY1,PTRSMRVLCQ,MNTEELELLSDSKYRNYVAAIDKALKNFEYSSEWADLISALGKLNK...,MNTEELELLSDSKYRNYVAAIDKALKNFEYSSEWADLISALGKLNK...,2,HsaEX0020714,...,0.00,0.00,144.332670,Nan,HsaEX0020714,Incl_main,ENSP00000195654,hg38,MNTEELELLSDSKYRNYVAAIDKALKNFEYSSEWADLISALGKLNK...,2465
207,207,31,31,15767,TENM3,AHYLDKIVK,MDVKERRPYCSLTKSRREKERRYTNSSADNEECRVPTQKSYSSSET...,MDVKERRPYCSLTKSRREKERRYTNSSADNEECRVPTQKSYSSSET...,2,HsaEX0044638,...,NaN,NaN,16.602430,AHYLDKIVK,HsaEX0044638,Incl_main,ENST00000511685fB4855,hg38,NaN,2708
208,208,89,89,60013,ITPR1,LPPAPDSENATE,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,2,HsaEX0032566,...,3.92,0.00,27.261058,LPPAPDSENATE,HsaEX0032566,Incl_main,ENSP00000306253,hg38,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,2758
209,209,90,90,60014,ITPR1,ELEPSPPLRQLEDHKR,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,2,HsaEX0032567,...,6.04,6.33,14.317807,ELEPSPPLRQLEDHKR,HsaEX0032567,Incl_main,ENSP00000306253,hg38,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,2758
210,210,88,88,60012,ITPR1,LISIDELDNAE,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,2,HsaEX0032565,...,0.00,0.00,52.362792,LISIDELDNAE,HsaEX0032565,Incl_main,ENSP00000306253,hg38,MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDL...,2758
211,211,163,163,133767,TENM4,AHYLDRVVK,MDVKERKPYRSLTRRRDAERRYTSSSADSEEGKAPQKSYSSSETLK...,MDVKERKPYRSLTRRRDAERRYTSSSADSEEGKAPQKSYSSSETLK...,2,HsaEX6003982,...,NaN,NaN,6.309089,AHYLDRVVK,HsaEX6003982,Incl_main,ENSP00000278550,hg38,MDVKERKPYRSLTRRRDAERRYTSSSADSEEGKAPQKSYSSSETLK...,2769
212,212,92,92,62336,PIEZO2,SIKKKLPIHQN,MASEVVCGLIFRLLLPICLAVACAFRYNGLSFVYLIYLLLIPLFSE...,MASEVVCGLIFRLLLPICLAVACAFRYNGLSFVYLIYLLLIPLFSE...,2,HsaEX6038146,...,NaN,NaN,8.888438,SIKKKLPIHQN,HsaEX6038146,Incl_main,ENSP00000463094,hg38,MASEVVCGLIFRLLLPICLAVACAFRYNGLSFVYLIYLLLIPLFSE...,2777
213,213,128,128,100288,FRYL,QMEILA,MSNITIDPDVKPGEYVIKSLFAEFAVQAEKKIEVVMAEPLEKLLSR...,MSNITIDPDVKPGEYVIKSLFAEFAVQAEKKIEVVMAEPLEKLLSR...,2,HsaEX0026468,...,4.44,6.96,9.123645,QMEILA,HsaEX0026468,Incl_main,ENSP00000351113,hg38,MSNITIDPDVKPGEYVIKSLFAEFAVQAEKKIEVVMAEPLEKLLSR...,3013
214,214,43,43,25523,FRY,QMESLA,MASQQDSGFFEISIKYLLKSWSNTSPVGNGYIKPPVPPASGTHREK...,MASQQDSGFFEISIKYLLKSWSNTSPVGNGYIKPPVPPASGTHREK...,2,HsaEX0026454,...,9.50,13.59,9.596636,QMESLA,HsaEX0026454,Incl_main,ENST00000542859fB2823,hg38,NaN,3019
215,215,82,82,56792,UNC80,SEPNVLDDSQGLAAEGSLS,MVKRKSSEGQEQDGGRGIPLPIQTFLWRQTSAFLRPKLGKQYEASC...,MVKRKSSEGQEQDGGRGIPLPIQTFLWRQTSAFLRPKLGKQYEASC...,2,HsaEX0069407,...,NaN,NaN,7.952467,SEPNVLDDSQGLAAEGSLS,HsaEX0069407,Incl_main,ENSP00000391088,hg38,MVKRKSSEGQEQDGGRGIPLPIQTFLWRQTSAFLRPKLGKQYEASC...,3258
216,216,120,120,93857,CELSR3,GLRGA,MMARRPPWRGLGGRSTPILLLLLLSLFPLSQEELGGGGHQGWDPGL...,MMARRPPWRGLGGRSTPILLLLLLSLFPLSQEELGGGGHQGWDPGL...,2,HsaEX0014560,...,0.00,0.00,15.657753,GLRGA,HsaEX0014560,Incl_main,ENST00000164024fB1550,hg38,NaN,3317
217,217,225,225,167705,RELN,LV,MERSGWARQTFLLALLLGATLRARAAAGYYPRFSPFFFLCTHHGEL...,MERSGWARQTFLLALLLGATLRARAAAGYYPRFSPFFFLCTHHGEL...,2,HsaEX0053031,...,NaN,NaN,20.096071,LV,HsaEX0053031,Incl_main,ENSP00000392423,hg38,MERSGWARQTFLLALLLGATLRARAAAGYYPRFSPFFFLCTHHGEL...,3460
218,218,205,205,166286,MYO15A,IK,MAKEEDEEKKAKKGKKGKKAPEPEKPKRSLKGTSRLFMGFRDRTPK...,MAKEEDEEKKAKKGKKGKKAPEPEKPKRSLKGTSRLFMGFRDRTPK...,2,HsaEX1024785,...,NaN,NaN,inf,IK,HsaEX1024785,Incl_main,ENSP00000205890,hg38,NaN,3530
219,219,68,68,46307,VPS13C,GRKRKKHKKHFKKPFKGLDRSK,MVLESVVADLLNRFLGDYVENLNKSQLKLGIWGGNVALDNLQIKEN...,MVLESVVADLLNRFLGDYVENLNKSQLKLGIWGGNVALDNLQIKEN...,2,HsaEX0070504,...,0.00,0.00,55.327118,GRKRKKHKKHFKKPFKGLDRSK,HsaEX0070504,Incl_main,ENSP00000261517,hg38,NaN,3753
220,220,67,67,46306,VPS13C,GTHSGEFIYGLENFVYKDIKP,MVLESVVADLLNRFLGDYVENLNKSQLKLGIWGGNVALDNLQIKEN...,MVLESVVADLLNRFLGDYVENLNKSQLKLGIWGGNVALDNLQIKEN...,2,HsaEX0070503,...,0.76,0.00,46.409656,GTHSGEFIYGLENFVYKDIKP,HsaEX0070503,Incl_main,ENSP00000261517,hg38,NaN,3753
221,221,186,186,155824,TRRAP,ESISECGRCPLSPFCQFE,MAFVATQGATVVDQTTLMKKYLQFVAALTDVNTPDETKLKMMQEVS...,MAFVATQGATVVDQTTLMKKYLQFVAALTDVNTPDETKLKMMQEVS...,2,HsaEX0067487,...,3.74,3.52,6.591994,ESISECGRCPLSPFCQFE,HsaEX0067487,Incl_main,ENSP00000352925,hg38,MAFVATQGATVVDQTTLMKKYLQFVAALTDVNTPDETKLKMMQEVS...,3859
222,222,187,187,155825,TRRAP,PAMEGVE,MAFVATQGATVVDQTTLMKKYLQFVAALTDVNTPDETKLKMMQEVS...,MAFVATQGATVVDQTTLMKKYLQFVAALTDVNTPDETKLKMMQEVS...,2,HsaEX0067471,...,0.00,0.00,14.707185,PAMEGVE,HsaEX0067471,Incl_main,ENSP00000394645,hg38,MAFVATQGATVVDQTTLMKKYLQFVAALTDVNTPDETKLKMMQEVS...,3873
223,223,158,158,131928,ANK2,MMVNRTTE,MMNEDAAQKSDSGEKFNGSSQRRKRPKKSDSNASFLRAARAGNLDK...,MMNEDAAQKSDSGEKFNGSSQRRKRPKKSDSNASFLRAARAGNLDK...,2,HsaEX0004128,...,NaN,NaN,7.171345,MMVNRTTE,HsaEX0004128,Incl_main,ENSP00000349588,hg38,MMNEDAAQKSDSGEKFNGSSQRRKRPKKSDSNASFLRAARAGNLDK...,3957
224,224,91,91,60126,ANK3,SPKI,MAHAASQLKKNRDLEINAEEEPEKKRKHRKRSRDRKKKSDANASYL...,MAHAASQLKKNRDLEINAEEEPEKKRKHRKRSRDRKKKSDANASYL...,2,HsaEX0004145,...,0.00,0.00,6.443628,SPKI,HsaEX0004145,Incl_main,ENSP00000482307,hg38,XEDAMTGDTDKYLGPQDLKELGDDSLPAEGYMGFSLGARSASPKIS...,4381
225,225,23,23,13205,PLEC,HWRAE,MSGEDAEVRAVSEDVSNGSSGSPSPGDTLPWNLGKTQRSRRSGGGA...,MSGEDAEVRAVSEDVSNGSSGSPSPGDTLPWNLGKTQRSRRSGGGA...,2,HsaEX0048202,...,1.39,0.00,23.577620,HWRAE,HsaEX0048202,Incl_main,ENSP00000437303,hg38,MSGEDAEVRAVSEDVSNGSSGSPSPGDTLPWNLGKTQRSRRSGGGA...,4591
226,226,130,130,101679,LRP2,NEPQP,MDRGPAAVACTLLLALVACLAPASGQECDSAHFRCGSGHCIPADWR...,MDRGPAAVACTLLLALVACLAPASGQECDSAHFRCGSGHCIPADWR...,2,HsaEX0036425,...,NaN,NaN,5.315507,NEPQP,HsaEX0036425,Incl_main,ENST00000263816fB3956,hg38,NaN,4660
227,227,116,116,83648,RYR2,VTGSQRSK,MADGGEGEDEIQFLRTDDEVVLQCTATIHKEQQKLCLAAEGFGNRL...,MADGGEGEDEIQFLRTDDEVVLQCTATIHKEQQKLCLAAEGFGNRL...,2,HsaEX0056060,...,NaN,NaN,5.450353,VTGSQRSK,HsaEX0056060,Incl_main,ENST00000366574fB6093,hg38,NaN,4975
228,228,25,25,14558,RYR1,AGDIQ,MGDAEGEDEVQFLRTDDEVVLQCSATVLKEQLKLCLAAEGFGNRLC...,MGDAEGEDEVQFLRTDDEVVLQCSATVLKEQLKLCLAAEGFGNRLC...,2,HsaEX0056040,...,NaN,0.00,9.988890,AGDIQ,HsaEX0056040,Incl_main,ENSP00000352608,hg38,MGDAEGEDEVQFLRTDDEVVLQCSATVLKEQLKLCLAAEGFGNRLC...,5038
229,229,24,24,14113,PCLO,GQVMVVQNA,MGNEASLEGEGLPEGLAAAAAAGGGASGAGSPSHTAIPAGMEADLS...,MGNEASLEGEGLPEGLAAAAAAGGGASGAGSPSHTAIPAGMEADLS...,2,HsaEX0045907,...,NaN,NaN,12.599450,GQVMVVQNA,HsaEX0045907,Incl_main,ENSP00000334319,hg38,MGNEASLEGEGLPEGLAAAAAAGGGASGAGSPSHTAIPAGMEADLS...,5142
230,230,71,71,47256,SYNE1,SMHRGSP,MATSRGASRCPRDIANVMQRLQDEQEIVQKRTFTKWINSHLAKRKP...,MATSRGASRCPRDIANVMQRLQDEQEIVQKRTFTKWINSHLAKRKP...,2,HsaEX0063155,...,0.00,2.35,54.403480,SMHRGSP,HsaEX0063155,Incl_main,ENSP00000396024,hg38,MATSRGASRCPRDIANVMQRLQDEQEIVQKRTFTKWINSHLAKRKP...,8749